### PR TITLE
Data analysis

### PR DESCRIPTION
**Pull request by lisabdj**
Hi everyone !

First of all, happy new year :)

I open this Pull Request for data analysis. I have already started the analyis in the file analysis.ipynb. After a meeting with @pierrepo, i have to correct some parts and add a graph.

### CODE REVIEW

**Comment by pierrepo** [comment]
Many thanks @lisabdj  :tada: 
Maybe the script `analysis.py` is not necessary anymore and you should remove it.

**Comment by lisabdj** [comment]
Ok, thanks, I deleted the script analysis.py.

I have a question @pierrepo : 
I need the module "yaml" to create lists containing the extensions of MD engines.
The module "pyyaml" is already installed in my environnement. But, when I want to launch my notebook analysis.ipynb in Jupyterlab, I have the message "No module named 'yaml'". Is the module compatible with Juputerlab ?

**Comment by pierrepo** [comment]
> Is the module compatible with Juputerlab ?
Yes. Absolutely. By default, all non-interactive Python modules (such as `pyyaml`) are compatible with Jupyter Lab. 
Did you activate the `mdws` environment first?
Did you update your `mdws` environment with the command?
```
mamba env update -f binder/environement.yml
```

**Comment by pierrepo** [comment]
@lisabdj did you manage to make it work?
Could you please push the last changes?

**Comment by lisabdj** [comment]
> did you manage to make it work?

**Comment by lisabdj** [comment]
Sorry for the false manipulation.

Thank you @pierrepo , I have imported the yaml module thanks to your order.

**Comment by lisabdj** [comment]
I updated the file query.yml.

The filetype

**Comment by lisabdj** [comment]
I have updated the file query.yml.

The filetype "top" is included in Gromacs and Amber. And, the filetype "prm" is included in Namd and Amber.
But, to simplify the analyses, I consider that "top" is only a filetype of Gromacs and prm a filetype of Namd.

Moreover, I added the line "category" to indicate if the type of the filetype is coordinate, topology or trajectory.

**Comment by pierrepo** [comment]
Thanks @lisabdj 
Could please commit `query.yml` into this branch to get the changes you made?

**Comment by lisabdj** [comment]
@pierrepo, I made the corrections you asked for at our last meeting.
I exported the notebook in html format.

**Comment by pierrepo** [comment]
Many thanks @lisabdj 
This looks very nice.

**Pull request merged**
